import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import google.generativeai as genai
from typing import List
from dotenv import load_dotenv
load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError("GEMINI_API_KEY environment variable not set.")

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel('gemini-1.5-pro-latest')

app = FastAPI()

# Define the request body model
class CommentsRequest(BaseModel):
    comments: List[str]

@app.post("/summarize_comments")
async def summarize_social_media_comments(request: CommentsRequest):
    """
    Receives a list of social media comments and returns a summary generated by the Gemini API.
    """
    if not request.comments:
        raise HTTPException(status_code=400, detail="No comments provided.")
    comments_text = "\n".join(request.comments)

    # Create the prompt for the Gemini API
    prompt = f"""
    Summarize the following social media comments. Focus on the main topics, sentiments (positive, negative, neutral), and any recurring themes.
    Make sure they're comments, if you don't see any comments, say "No comments found".

    Comments:
    {comments_text}

    Summary:
    """

    try:
        response = model.generate_content(prompt)
        if response and response.parts:
             summary = "".join(part.text for part in response.parts if part.text)
             return {"summary": summary}
        else:
             # Handle cases where the API returns an empty or unexpected response
             raise HTTPException(status_code=500, detail="Failed to generate summary from API.")


    except Exception as e:
        # Log the error for debugging
        print(f"An error occurred: {e}")
        raise HTTPException(status_code=500, detail=f"An internal error occurred: {e}")
